%ifndef ASC_IR_INC
%define ASC_IR_INC

%define IR_NOP         0
%define IR_CONST       1
%define IR_LOAD        2
%define IR_STORE       3
%define IR_ADD         4
%define IR_SUB         5
%define IR_MUL         6
%define IR_DIV         7
%define IR_CMP         8
%define IR_LABEL       9
%define IR_JUMP        10
%define IR_JZ          11
%define IR_CALL        12
%define IR_RET         13

%endif
